# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: kotest
        name: Kotest (Kotlin tests)
        entry: ./gradlew ktlintCheck test
        language: system
        types: [kotlin]
        pass_filenames: false
      - id: ktlint
        name: Ktlint (Kotlin linter)
        entry: ./gradlew ktlintFormat
        language: system
        types: [kotlin]
        pass_filenames: false
      - id: pre-push
        name: Pre-push (Testcontainers, Detekt, Gitleaks, Dependency Check)
        entry: .github/hooks/pre-push.sh
        language: script
        stages: [push]
        pass_filenames: false
