build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

processors:
  active: true

console-reports:
  active: true

output-reports:
  active: true
  xml:
    active: true
  html:
    active: true
  txt:
    active: false

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: true
    value: 120
